/*
 * generated by Xtext 2.15.0
 */
package org.xtext.mydsladventure.rpg.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RPGProposalProvider extends AbstractRPGProposalProvider {
}
