/*
 * generated by Xtext 2.15.0
 */
package org.xtext.mydsladventure.rpg.validation

import java.util.ArrayList
import org.eclipse.xtext.validation.Check
import myDSLAdventure.Room
import myDSLAdventure.MyDSLAdventurePackage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RPGValidator extends AbstractRPGValidator {

	@Check
	def checkUniqueRoomNames(Room room) {
		
		val roomExitNames = new ArrayList<String>();		
		var index = 0;
		
		for(exit : room.exits) {
			
			if(roomExitNames.contains(exit.action)) {
				error("Duplicate action '" + exit.action+"' in room '" + room.name + "'",
					exit, MyDSLAdventurePackage.Literals.EXIT__ACTION)
			} else {
				roomExitNames.add(exit.action)
			}
			
			index++
		}
	}
}
