<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myDSLAdventure" nsURI="http://myDSLAdventure" nsPrefix="myDSLAdventure">
  <eClassifiers xsi:type="ecore:EClass" name="RoomList" eSuperTypes="#//GameElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" upperBound="-1" eType="#//Room"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gameTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameelementlist" upperBound="-1"
        eType="#//GameElementList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameElementList" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExitList" eSuperTypes="#//GameElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" upperBound="-1"
        eType="#//RoomId" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonsterList" eSuperTypes="#//GameElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monsterstatement" upperBound="-1"
        eType="#//MonsterStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" eSuperTypes="#//GameElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startRoom" lowerBound="1"
        eType="#//RoomId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="healthPoints" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weaponid" eType="#//WeaponId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonsterDescription" eSuperTypes="#//MonsterStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseWeaponName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" eType="#//WeaponId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonsterStatement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monsterId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonsterPlacement" eSuperTypes="#//MonsterStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//RoomId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeaponList" eSuperTypes="#//GameElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" upperBound="-1"
        eType="#//Weapon" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Weapon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weaponid" lowerBound="1"
        eType="#//WeaponId" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomid" upperBound="-1"
        eType="#//RoomId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeaponId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weaponId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
